'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class About
    
    '''<summary>
    '''petName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents petName As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''age control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents age As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''month control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents month As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''breed control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents breed As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''pet_Type control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pet_Type As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''sex control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sex As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''holder_name control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents holder_name As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''contact control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents contact As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''address control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents address As Global.System.Web.UI.HtmlControls.HtmlTextArea
    
    '''<summary>
    '''date control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents [date] As Global.DevExpress.Web.Bootstrap.BootstrapDateEdit
    
    '''<summary>
    '''details control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents details As Global.System.Web.UI.HtmlControls.HtmlTextArea
    
    '''<summary>
    '''bw control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bw As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''lab control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lab As Global.System.Web.UI.HtmlControls.HtmlTextArea
    
    '''<summary>
    '''fee control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fee As Global.System.Web.UI.HtmlControls.HtmlTextArea
    
    '''<summary>
    '''rx control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rx As Global.System.Web.UI.HtmlControls.HtmlTextArea
    
    '''<summary>
    '''amount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents amount As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''btn_Submit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_Submit As Global.System.Web.UI.WebControls.Button
End Class
