'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Admit
    
    '''<summary>
    '''hdn_addID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdn_addID As Global.DevExpress.Web.ASPxTextBox
    
    '''<summary>
    '''hdn_opdnum control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdn_opdnum As Global.DevExpress.Web.ASPxTextBox
    
    '''<summary>
    '''opd_num control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents opd_num As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''petName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents petName As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''contact control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents contact As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''holder_name control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents holder_name As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''btnbt_Search control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnbt_Search As Global.DevExpress.Web.ASPxButton
    
    '''<summary>
    '''gv_OPD control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gv_OPD As Global.DevExpress.Web.Bootstrap.BootstrapGridView
    
    '''<summary>
    '''ods_opd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ods_opd As Global.System.Web.UI.WebControls.ObjectDataSource
    
    '''<summary>
    '''gv_admit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gv_admit As Global.DevExpress.Web.Bootstrap.BootstrapGridView
    
    '''<summary>
    '''ods_admit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ods_admit As Global.System.Web.UI.WebControls.ObjectDataSource
    
    '''<summary>
    '''popup_add control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents popup_add As Global.DevExpress.Web.Bootstrap.BootstrapPopupControl
    
    '''<summary>
    '''lbl_addID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_addID As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''dedit_addday control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dedit_addday As Global.DevExpress.Web.Bootstrap.BootstrapDateEdit
    
    '''<summary>
    '''btn_pup_submit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_pup_submit As Global.DevExpress.Web.Bootstrap.BootstrapButton
    
    '''<summary>
    '''btn_pup_cancel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_pup_cancel As Global.DevExpress.Web.Bootstrap.BootstrapButton
End Class
