'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class AppointDetail
    
    '''<summary>
    '''hdn_id control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdn_id As Global.DevExpress.Web.ASPxTextBox
    
    '''<summary>
    '''header_h4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents header_h4 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''para1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents para1 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''para2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents para2 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''BootstrapPageControl1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BootstrapPageControl1 As Global.DevExpress.Web.Bootstrap.BootstrapPageControl
    
    '''<summary>
    '''gv_detail2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gv_detail2 As Global.DevExpress.Web.Bootstrap.BootstrapGridView
    
    '''<summary>
    '''ods_detail2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ods_detail2 As Global.System.Web.UI.WebControls.ObjectDataSource
    
    '''<summary>
    '''gv_detail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gv_detail As Global.DevExpress.Web.Bootstrap.BootstrapGridView
    
    '''<summary>
    '''ods_detail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ods_detail As Global.System.Web.UI.WebControls.ObjectDataSource
End Class
