'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Management
    
    '''<summary>
    '''opd_num control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents opd_num As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''petName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents petName As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''petType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents petType As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''holder_name control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents holder_name As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''btnbt_Search control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnbt_Search As Global.DevExpress.Web.Bootstrap.BootstrapButton
    
    '''<summary>
    '''gv_OPD control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gv_OPD As Global.DevExpress.Web.Bootstrap.BootstrapGridView
    
    '''<summary>
    '''ods_opd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ods_opd As Global.System.Web.UI.WebControls.ObjectDataSource
End Class
